### ISSUE TITLE
Support seat types

### ISSUE THREAD

**Issue by MathewBurnett** [mintopia/control#7]
Have a seating plan that has a mapping between seat types and ticket types. Examples like
* staff ticket for staff seat
* VIP 
*  Volunteer etc

**Comment by davidyell** [comment]
Would be nice to know if there are any accessible seats on the plan so that folks with differing levels of ability can ensure they can get the right seat for their needs.

**Comment by t3rminalV** [comment]
To further enhance this would be good to be able to group seats together and then assign the rights to seat there not only based on ticket type, but also clan, or even individual people to make things a bit more flexible.
